// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmbn5fXk8G7NUUNZU5tcqM3nJCKlPI7Z4',
    appId: '1:559601591516:web:d302e6e19471d7ecce4019',
    messagingSenderId: '559601591516',
    projectId: 'app-udipsai-hc05',
    authDomain: 'app-udipsai-hc05.firebaseapp.com',
    storageBucket: 'app-udipsai-hc05.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwp7QwwG6EBlbJNzmU3CEkRYiv5h5vD_k',
    appId: '1:559601591516:android:bed23a0f946523e4ce4019',
    messagingSenderId: '559601591516',
    projectId: 'app-udipsai-hc05',
    storageBucket: 'app-udipsai-hc05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZlMo3ROxW-cr3nIDEgm-KolmXDfSiHJM',
    appId: '1:559601591516:ios:21403279d366a6fece4019',
    messagingSenderId: '559601591516',
    projectId: 'app-udipsai-hc05',
    storageBucket: 'app-udipsai-hc05.firebasestorage.app',
    iosBundleId: 'com.example.hc05Udipsai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZlMo3ROxW-cr3nIDEgm-KolmXDfSiHJM',
    appId: '1:559601591516:ios:21403279d366a6fece4019',
    messagingSenderId: '559601591516',
    projectId: 'app-udipsai-hc05',
    storageBucket: 'app-udipsai-hc05.firebasestorage.app',
    iosBundleId: 'com.example.hc05Udipsai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmbn5fXk8G7NUUNZU5tcqM3nJCKlPI7Z4',
    appId: '1:559601591516:web:04f46271ce556cf2ce4019',
    messagingSenderId: '559601591516',
    projectId: 'app-udipsai-hc05',
    authDomain: 'app-udipsai-hc05.firebaseapp.com',
    storageBucket: 'app-udipsai-hc05.firebasestorage.app',
  );
}
